# Generated by Django 5.2 on 2025-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the announcement/update message.')),
                ('unique_identifier', models.CharField(help_text="Unique ID for this announcement (e.g., 'update-2025-05-10')", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this announcement currently active to be shown to users?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
