# Generated by Django 5.2 on 2025-05-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_location_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_longitude',
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to='accounts.profile')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
