# Generated by Django 5.2 on 2025-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_savedlocation_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlocation',
            name='location_type_label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('school', 'School'), ('vacation', 'Vacation Spot'), ('relative', "Relative's House"), ('other', 'Other')], default='other', max_length=20, verbose_name='Location Label'),
        ),
    ]
