# Generated by Django 5.2 on 2025-05-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_savedlocation_location_type_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlocation',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications for alerts at this location'),
        ),
    ]
