# Generated by Django 5.2 on 2025-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_savedlocation_receive_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seen_announcement_identifiers',
            field=models.JSONField(blank=True, default=list, help_text='List of unique identifiers of announcements seen by the user.'),
        ),
    ]
