# Generated by Django 5.2 on 2025-05-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_seen_announcement_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, help_text="User's state/province (e.g., OK, Texas)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(blank=True, help_text="User's town/city", max_length=100, null=True),
        ),
    ]
