# Generated by Django 5.2 on 2025-06-05 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_family_familyinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who have accepted an invitation to join this family.', related_name='families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family',
            name='owner',
            field=models.OneToOneField(help_text='The primary user who owns the family plan subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_family', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyinvitation',
            name='email_to_invite',
            field=models.EmailField(help_text='Email address of the person being invited.', max_length=254),
        ),
    ]
