# Generated by Django 5.2 on 2025-05-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID (e.g., price_ H5ggL5LP...)', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Display price (e.g., 5.00)', max_digits=6)),
                ('features', models.TextField(blank=True, help_text='Optional description of features')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(help_text='Stripe Subscription ID (e.g., sub_...)', max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(help_text='Stripe Customer ID (e.g., cus_...)', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='incomplete', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End date of the current billing cycle', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, help_text='The Plan the user is subscribed to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
