# Generated by Django 5.2 on 2025-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_notifiedalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['display_order', 'tier_name', 'billing_interval']},
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', help_text='The billing frequency (e.g., month or year)', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which to display plan tiers (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier_name',
            field=models.CharField(default='Default', help_text="A common name for this plan tier (e.g., 'Premium') to group monthly/yearly versions.", max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(blank=True, help_text='Optional description of features (use line breaks for bullets)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Display price (e.g., 5.00 for this interval)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(help_text='Stripe Price ID (e.g., price_H5ggL5LP...)', max_length=100, unique=True),
        ),
    ]
