# Generated by Django 5.2 on 2025-06-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_options_plan_billing_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Can users currently subscribe to this plan?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_visible_on_page',
            field=models.BooleanField(default=True, help_text='Should this plan be shown on the plan selection page?'),
        ),
    ]
